language: node_js
services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
before_install:
  # Travis no tiene buen soporte para cambiar la versión de Postgre, ver:
  # https://travis-ci.community/t/test-against-postgres-12/6768/8
  - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run db:init
env:
  global:
    - SQL_USERNAME=postgres
    - SQL_TEST_DATABASE=travis_ci_test
    - SQL_PORT=5433
    - PGPORT=5433
    - NODE_ENV=test
deploy:
  provider: heroku
  app: unahur-covid-api
  api_key:
    secure: ZSLM/VCDDxlPwx/jvLuQwhNbUqh6/GU2zsEy0GY5QNWQ67qoNlOdnXsV2IJ7A120XIjP86o7IzP6Qhgdq3YY/EzCl+YIt2Y8E6IAsT+an3n5Wp8uZAFhVpbiL//J4Fo767H2h/qFc877LhU6wXxye/1f7WYBAhHunNQQvMwOCcLZc6ib3PFusghyLSXYztetFs+qrVTrDEERWgyFmy3B6LONt2FPRNR0HqU/LgtBENA6tUgRuo+EihlHXpIJhK9Z/twU3czKo++j2c9Uw0pByXwelmMvQ6pV087gKrX3GCoE3dbodS0TommFHHvoPllUoxejvvdOSI7auOxwwDKXVyVKhP2h0VLpW+wAMBFsNNqqmoNVksaFDjqxLdvh4tTe6a+U+bkdiBLp3jc87PsWufsWe2SnnOSxU8OjV3wx7cgQ8/HibvTsLmje7SJ4XazJmEyz6TZniGvEIodCEXNtc253+VLHdTO1RFQ97qVGNWVToreWI2kS6OxZCijq3QIjveMLMKbPR6SDqX3HTVB92+f5UdixC+hDu1hP6C4xR5qsWmQ6H/O2hwJrhIwBo69+NpScMlWca3yBaPnjxMVzpPL2xXnSJaIerN+l3osMkQnn9yjZKRUymJ98JTuiZxUpWBAAsoOqIAB6LhPqEkABY7i2ogskk/c/F0qpZzA5z3s=
