language: node_js
services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
# Travis no tiene buen soporte para cambiar la versión de Postgre, ver:
# https://travis-ci.community/t/test-against-postgres-12/6768/8
before_install:
  - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run db:init
env:
  global:
    - SQL_USERNAME=postgres
    - SQL_TEST_DATABASE=travis_ci_test
    - SQL_PORT=5433
    - PGPORT=5433
    - NODE_ENV=test
    - secure: oGJNIS637bF24vuJL1UXpyl6AGKaxs16mc5xz1bWojdaJdqWtfZU18fWNVne1dQWa7AxcN+67GJ4y7Mv48mgeTrCb7vYFHvzoTz+FTMcA2RzS/h8/mCkI2Ib2jp+wpcsF7PiutjPLRQedbRNTgW/bKtJxfOp9P2vHtOx5Yk/ZRffW4oDHneinkeBM1ZDsKb3GZg66uQe4qfyqC+5TMQPZ0/ai3bjGvMuto4Oo/W/BXzHZJ77qBbIPujslSyAlPiBSHWlC99SuBZ/zC3a9Jm0cg+ZboCW7A2adMS2L3ge69G4GNrBmG3KgyiATcSFi0BmszjNsekYlfmQEWGfX5XCI78zK+ruW1wCLd3pzG7GD5h1OWXmjJzumRO/yyCNUZM1g4l/CXzRx2U93HJzpuwwISINOdxfXZqXfY7zccYhVWSlagNEvWgUMJXfn1UmC6uWCF2+XnlV5MRc7KfmVRFGpZ/YfTSRig+I1AG0jUc6DcpU0wDLMnj52gzEeY39ly+dlAQOczJWavaTCkc9bR/wNSlJwnoTwBT75l/pM2QUXFbTVtQMAha9pF4b51+XF3c95vO8giAY9ISfDfgOSA+Oulubd1dneiYnhlEgX4wadoANZgO+C4PvK4a+3y33RsbBIh5Ze5b8dwv2LNdYEwpgomyXMOtE5Qtsy1sim73vpzY=
deploy:
  - provider: heroku
    app: unahur-covid-api
    api_key:
      secure: ZSLM/VCDDxlPwx/jvLuQwhNbUqh6/GU2zsEy0GY5QNWQ67qoNlOdnXsV2IJ7A120XIjP86o7IzP6Qhgdq3YY/EzCl+YIt2Y8E6IAsT+an3n5Wp8uZAFhVpbiL//J4Fo767H2h/qFc877LhU6wXxye/1f7WYBAhHunNQQvMwOCcLZc6ib3PFusghyLSXYztetFs+qrVTrDEERWgyFmy3B6LONt2FPRNR0HqU/LgtBENA6tUgRuo+EihlHXpIJhK9Z/twU3czKo++j2c9Uw0pByXwelmMvQ6pV087gKrX3GCoE3dbodS0TommFHHvoPllUoxejvvdOSI7auOxwwDKXVyVKhP2h0VLpW+wAMBFsNNqqmoNVksaFDjqxLdvh4tTe6a+U+bkdiBLp3jc87PsWufsWe2SnnOSxU8OjV3wx7cgQ8/HibvTsLmje7SJ4XazJmEyz6TZniGvEIodCEXNtc253+VLHdTO1RFQ97qVGNWVToreWI2kS6OxZCijq3QIjveMLMKbPR6SDqX3HTVB92+f5UdixC+hDu1hP6C4xR5qsWmQ6H/O2hwJrhIwBo69+NpScMlWca3yBaPnjxMVzpPL2xXnSJaIerN+l3osMkQnn9yjZKRUymJ98JTuiZxUpWBAAsoOqIAB6LhPqEkABY7i2ogskk/c/F0qpZzA5z3s=
  - provider: heroku
    app: unahur-visitas-api
    on:
      tags: true
    api_key:
      secure: yW5fzx0QEtyWEFz3rs2cRCI50OIlkEU0CBQwuneXcQ6QzaE8l/1mCRzi2SASluAMPrU1u07skv5MpCiYcugigXBA4MGW2HNAOjU3b/LNMJDe+OoVdOxLbuia9igbi5tsk+y7z+/ckVZ86PkW8OEnMbn8sPb3YIFOC0eYtD18/TnmEdTcH9PprcpS8lrxf5NALJeWnltG8JwPV89ROpEmyEGyR7vGTRe7fK/1ChOdFh8JsJuVntV3aO4YthjRLiLDLoz2AD8NOmPtvRTrgx1CeHFhY3QT4hO6y5E7U3NZ9L4v2ioRO+xeqWjzwazGcZWs9kByJBSfkvi+AEnv+qq17C8Li6m2yELoUp14U5IWyruHkE+iJaHZJAZzVCTQg64i6N2mupf3JCIEzpghZZcDO75lXnpDdXlbQkdq3oA1ZEqjhUCQ+gK/6MvW7Jt8FCWnD+dpQNvGMzhLWkDmAQZ37gNVX+qHGNJlZXBcpIpNWJdkdy5PbiJK7ewhLYOFtoWy5BSe4dvYbdRZ1o3ojQFfS97/8TywTsqTHjUh5FqCfKhY0ocVulHC6cI0Jg1Dr9yv3EpbscxYiUyFy0FAyTZxvEhYYkNRL2+rk6jHdo/pJ5R91CBJNIPREAE1a/4bYUNn5x1gd4vlnlnXRqVgQ6adLJR3++0r/D2u23pLkNerKy4=
after_success:
  - if [[ $TRAVIS_BRANCH != "master" ]]; then ./bin/notify-travis-discord.sh success $WEBHOOK_URL; fi
after_failure:
  - if [[ $TRAVIS_BRANCH != "master" ]]; then ./bin/notify-travis-discord.sh failure $WEBHOOK_URL; fi
