name: Test and deploy

on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        ports:
          - 5432:5432
        image: postgres:12.5-alpine
        env:
          POSTGRES_DB: turnos_test
          POSTGRES_USER: turnos
          POSTGRES_PASSWORD: turnos1234
    env:
      NODE_ENV: test
      SQL_USERNAME: turnos
      SQL_PASSWORD: turnos1234
      SQL_TEST_DATABASE: turnos_test
    steps:
      - uses: actions/checkout@v2
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
      - run: npm ci
      - run: npm run db:init
      - run: npm run lint
      - run: npm test
